# Generated by Django 3.2.9 on 2021-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField()),
                ('time_received', models.DateTimeField()),
                ('time_processed', models.DateTimeField()),
            ],
        ),
    ]
